### ISSUE TITLE
Programm freezes on error 

### ISSUE THREAD

**Issue by tarikly** [nathanaday/RealTime-OCR#2]
Hey there!

I got this error while trying to execute you code.

```shell
ValueError: invalid literal for int() with base 10: '30.275726'
```

![image](https://user-images.githubusercontent.com/8581805/156919845-bfc802d4-547a-43d4-a588-7795e8399f48.png)

Python version: 3.9.4

**Comment by holo-holo** [comment]
I experienced the same problem.
May be we can not use tesserac Ver5.
Pls use tesserac Ver4.
https://digi.bib.uni-mannheim.de/tesseract/

**Comment by MajevSong** [comment]
> I experienced the same problem. May be we can not use tesserac Ver5. Pls use tesserac Ver4. https://digi.bib.uni-mannheim.de/tesseract/

ty, worked well for me (v4)

**Comment by nathanaday** [comment]
Apologies for the long delay! This should be fixed now.
